{% set version = "2025.0.5" %}
{% set name = "async-dsmz" %}
{% set python_min = "3.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/async_dsmz-{{ version }}.tar.gz
  sha256: 2b291b10d017fe8953de9525f833832f68c867be699dc0987d818a46775ca3c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps 
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
    - hatchling

  run:
    - python >={{ python_min }}
    - lpsn
    - aiohttp
    - bacdive
    - python-keycloak

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - async_dsmz
  commands:
    - pip check


about:
  home: https://github.com/Fabian-Bastiaanssen/Async_DSMZ
  summary: Asyncio wrappers for the DSMZ LPSN and BacDive APIs
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fabian-Bastiaanssen
